spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/hotel_reservation}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:vodanhtu1}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.springframework.web: ${SPRING_WEB_LOG_LEVEL:INFO}
    org.hibernate: ${HIBERNATE_LOG_LEVEL:INFO}

# Local profile specific configurations
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# EC2 profile specific configurations
---
spring:
  config:
    activate:
      on-profile: ec2
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  tomcat:
    max-threads: 200
    min-spare-threads: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized